version: "3.9"

services:
  #Flask Service
  flask_backend:
    build:
      context: ./backend
      target: development
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      TOKEN_EXPIRATION_DAYS: 5
      TOKEN_EXPIRATION_SECONDS: 30
      SECRET_KEY: "sdgdgfhfjsfgjdrg"
      MAIL_SERVER: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_DEFAULT_SENDER: "no-reply@flask-redis.test"
      CELERY_BROKER_URL: amqp://rabbit-user:rabbit-password@rabbitmq_broker:5672/
      CELERY_RESULT_BACKEND: rpc://
      CELERY_BROKER_TEST_URL: amqp://rabbit-user:rabbit-password@rabbitmq_broker:5672/
    ports:
      - 5678:5678
  #Nuxt Frontend Service
  nuxt_frontend:
    build:
      context: ./frontend
      target: development
    environment:
      NODE_ENV: development
    command: yarn dev -o
    # command: yarn dev-debug # for debugging WIP
  #Redis Stack Service
  redis_database:
    image: redis/redis-stack:7.0.2-RC1
    ports:
      - 8001:8001
  #Nginx Service
  nginx_server:
    volumes:
      - ./server/conf.d/development:/etc/nginx/conf.d

  mailhog:
    image: "mailhog/mailhog:latest"
    container_name: mailhog
    ports:
      - "${FORWARD_MAILHOG_PORT:-1025}:1025"
      - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
    networks:
      - backend-network
