version: "3.9"

services:
  #Flask Service
  backend:
    build:
      context: ./backend
      target: development
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    ports:
      - 5678:5678
  #Nuxt Frontend Service
  frontend:
    build:
      context: ./frontend
      target: development
    environment:
      NODE_ENV: development
    command: yarn dev -o
    # command: yarn dev-debug # for debugging WIP
  #Redis Stack Service
  database:
    image: redis/redis-stack:7.0.2-RC1
    ports:
      - 8001:8001
  #Nginx Service
  server:
    volumes:
      - ./server/conf.d/development:/etc/nginx/conf.d
